version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: payring-app:latest
    container_name: payring-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=sqlite:////app/instance/payring.db
    command: gunicorn --bind 0.0.0.0:8080 "app:create_app()"
    volumes:
      - payring_data:/app/instance

volumes:
  payring_data: